#require: rubocop-rails

ClassLength:
  Max: 150
Documentation:
  Enabled: false

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'
  TargetRubyVersion: 2.5


Metrics/LineLength:
  Max: 120
Metrics/AbcSize:
  Enabled: true
  Max: 20
Metrics/MethodLength:
#  CountComments: false  # count full line comments?
  Max: 20
#Metrics/BlockLength:
#  Enabled: false


# Rails:
#   Enabled: true
# Rails/SkipsModelValidations:
#   Enabled: false


# Security/Eval:
#   Enabled: false


# Style/ClassAndModuleChildren:
#   Enabled: false
# Style/Lambda:
#   EnforcedStyle: literal # always "->"" instead of line_count_dependent
# Style/StructInheritance:
#   Enabled: false # needed to allow Headless Policies of Pundit
# Style/ClassVars:
#   Description: 'Avoid the use of class variables.'
#   StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#no-class-vars'
#   Enabled: false
# Style/FrozenStringLiteralComment:
#   Enabled: false
# Style/AsciiComments:
#   Description: 'Use only ascii symbols in comments.'
#   StyleGuide: '#english-comments'
#   Enabled: false
# Style/RegexpLiteral:
#   Enabled: false